### ISSUE TITLE
New Logo Design For Online Cab Booking Android Application

### ISSUE THREAD

**Issue by zularizal** [parkouronit/Online-Cab-Booking-Android-Application#1]
Hi, I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by parkouronit** [comment]
I'm new here so do what ever u want!!

**Comment by zularizal** [comment]
Okay, please wait i will design a logo for this project

**Comment by parkouronit** [comment]
if want something in return then don't. . . coz I've got nothing to give you!!

**Comment by zularizal** [comment]
I do not want something for this, I only work on open source licensed projects. can you add the license to your project?

**Comment by zularizal** [comment]
if this project is open source, you can add license, is this open source project?

**Comment by parkouronit** [comment]
yup it is. . .

**Comment by zularizal** [comment]
Okay, please wait, i will design a logo for your project..

**Comment by zularizal** [comment]
Hi @parkouronit ,  tell me what is the name of this app and explain what is the function of this application?

**Comment by parkouronit** [comment]
Rovers for passenger(used for booking cab), Cabbies for Driver(used for getting cab requests) and a website Admin(to monitor things) that's all. . .

**Comment by zularizal** [comment]
So you need 3 similar logos?

**Comment by parkouronit** [comment]
yup

**Comment by zularizal** [comment]
Please wait, i designing it

**Comment by parkouronit** [comment]
ok Thank you!! 👍

**Comment by zularizal** [comment]
Hi @parkouronit  , I've made 3 similar logos, what do you think? is there anything you want to change? And what color do you like?

![logo](https://user-images.githubusercontent.com/38547278/40702821-6f1d507c-640d-11e8-8c3c-aad98fc609d7.png)

**Comment by parkouronit** [comment]
1st one's best. . .  you've a very great imagination. . .

**Comment by zularizal** [comment]
Hi @parkouronit , I've uploaded logo and icon files to drive, check this link.

https://drive.google.com/open?id=1I_Ud3pU7K-czT2y3uraCmK1YPcwhxyHJ

And also I have sent a pull request for you, please check #2
